### PR TITLE
Add GlobalOutagePolicy for Synthetic Monitor API

### PR DESCRIPTION
**Pull request by tshortess**
This PR creates a global_outage_policy class and updates the outage_handling_policy class to enable configuration of the consecutive runs in the global outage policy consistent with the Dynatrace Synthetic Monitor API.

### CODE REVIEW

**Comment by tshortess** [comment]
I changed the status of this PR to draft to test my changes, and in the process, I changed the module references in the last commit ([Changed module references for testing](https://github.com/dtcookie/dynatrace/pull/18/commits/01554d261cd10824406488e360d384c38e933526)
[01554d2](https://github.com/dtcookie/dynatrace/pull/18/commits/01554d261cd10824406488e360d384c38e933526)). Before I removed the draft, the PR was merged. Can you please revert the last commit so the module references are correct?

**Comment by Dynatrace-Reinhard-Pilz** [comment]
I just made the changes myself. No need to revert.

**Comment by tshortess** [comment]
Thanks, but it looks like there are 4 other files that weren't changed. Can you please update those as well?

- api/config/synthetic/monitors/http_synthetic_monitor_update.go
- api/config/synthetic/monitors/monitors_test.go
- api/config/synthetic/monitors/go.sum
- api/config/synthetic/monitors/go.mod

**Comment by Dynatrace-Reinhard-Pilz** [comment]
Thank you for the hint, didn't notice the other places. I've taken care of it.

**Pull request merged**
